In [45]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns

**INICIO DE CARGA DE ARCHIVO CSV**

In [46]:
#Carga desde un archivo .csv sin indice
df =pd.read_csv('Francia.csv')
df
#Inmuebles['Columna']=Inmuebles['Columna'].str.replace('%', '')

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,"Duplex avec vue, centre ville",269557,Isabelle,2010-10-24,"Lyon, France",I'm 47 years old. I enjoy books and arts. I'm ...,within a few hours,1.00,f,...,4.71,4.78,4.86,"Available with a mobility lease only (""bail mo...",f,1,1,1,0,0.33
1,1,Nice Flat in the center of Lyon,411285,Clementine,2011-02-26,"Lyon, France",Je travaille dans le cinéma et je voyage beauc...,within an hour,1.00,f,...,4.80,4.96,4.88,6938113058353,f,1,1,1,0,0.15
2,2,"Centre of old town,home sweet home",660135,Polali,2011-06-03,"Lyon, France","J'ai 34 ans , je suis animatrice auprès de per...",a few days or more,0.00,f,...,4.27,4.72,4.86,6938513221658,f,1,1,1,0,0.82
3,3,"Bel apartment, 2 rooms, Lyon center",670404,Sandrine,2011-06-06,"Lyon, France","We are a family with 3 daughters, aged 16-14-1...",NaN,NaN,f,...,4.89,4.89,4.95,693861800177,f,1,1,1,0,0.12
4,4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,832917,Giuseppina,2011-07-18,"Rhône-Alpes, France","Mon pays d'origine est l'Italie, mais je résid...",within an hour,1.00,f,...,4.86,4.83,4.88,6938112368465,f,2,2,2,0,2.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9888,9888,Havre de Paix au Cœur du 7ème,666633599,Adrian,2024-12-12,NaN,NaN,NaN,NaN,f,...,NaN,NaN,NaN,6938712751252,f,1,1,1,0,NaN
9889,9889,Le Duplex avec Rooftop,12466813,Hugues,2014-02-22,"Lyon, France",NaN,within an hour,1.00,f,...,NaN,NaN,NaN,6938713431341,f,1,1,1,0,NaN
9890,9890,L’opéra,417340177,Fifa,2021-08-07,"Lyon, France",NaN,within an hour,1.00,NaN,...,NaN,NaN,NaN,Exempt - hotel-type listing,t,5,4,4,0,NaN

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9891 entries, 0 to 9890
Data columns (total 51 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Unnamed: 0                                     9891 non-null   int64
 1   name                                           9891 non-null   object
 2   host_id                                        9891 non-null   int64
 3   host_name                                      9889 non-null   object
 4   host_since                                     9889 non-null   object
 5   host_location                                  8367 non-null   object
 6   host_about                                     3825 non-null   object
 7   host_response_time                             5235 non-null   object
 8   host_response_rate                             5235 non-null   float64
 9   host_is_superhost                              9680 non-null   object
 10  host_neighbourhood                             4347 non-null   object
 11  host_listings_count                            9889 non-null   float64
 12  host_total_listings_count                      9889 non-null   float64
 13  host_identity_verified                         9889 non-null   object
 14  neighbourhood_cleansed                         9891 non-null   object
 15  latitude                                       9891 non-null   float64
 16  longitude                                      9891 non-null   float64
 17  property_type                                  9891 non-null   object
 18  room_type                                      9891 non-null   object
 19  accommodates                                   9891 non-null   int64
 20  bathrooms                                      5466 non-null   float64
 21  bedrooms                                       8519 non-null   float64
 22  beds                                           5458 non-null   float64
 23  price                                          5470 non-null   float64
 24  minimum_nights                                 9891 non-null   int64
 25  maximum_nights                                 9891 non-null   int64
 26  minimum_minimum_nights                         9891 non-null   int64
 27  maximum_minimum_nights                         9891 non-null   int64
 28  minimum_maximum_nights                         9891 non-null   int64
 29  maximum_maximum_nights                         9891 non-null   int64
 30  minimum_nights_avg_ntm                         9891 non-null   float64
 31  maximum_nights_avg_ntm                         9891 non-null   float64
 32  availability_30                                9891 non-null   int64
 33  availability_60                                9891 non-null   int64
 34  availability_90                                9891 non-null   int64
 35  availability_365                               9891 non-null   int64
 36  number_of_reviews                              9891 non-null   int64
 37  number_of_reviews_ltm                          9891 non-null   int64
 38  number_of_reviews_l30d                         9891 non-null   int64
 39  last_review                                    8024 non-null   object
 40  review_scores_rating                           8024 non-null   float64
 41  review_scores_cleanliness                      8024 non-null   float64
 42  review_scores_checkin                          8021 non-null   float64
 43  review_scores_location                         8020 non-null   float64
 44  license                                        5916 non-null   object
 45  instant_bookable                               9891 non-null   object
 46  calculated_host_listings_count                 9891 non-null   int64
 47  calculated_host_listings_count_entire_homes    9891 non-null   int64
 48  calculated_host_listings_count_entire_homes.1  9891 non-null   int64
 49  calculated_host_listings_count_shared_rooms    9891 non-null   int64
 50  reviews_per_month                              8024 non-null   float64
dtypes: float64(16), int64(20), object(15)
memory usage: 3.8+ MB

**FILTRO PARA CINCO "HOST NAME" DIFERENTES**

In [16]:
#Agarrar un nombre de la columna de host_name
#filtro1=df.iloc[[5,8,12,34,50],3]   
#filtro1
filtro1=df[(df["host_name"]=="Isabelle")| (df["host_name"]=="Sandrine")| (df["host_name"]=="Polali")| (df["host_name"]=="Pablo")| (df["host_name"]=="Adrian")]
filtro1

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,"Duplex avec vue, centre ville",269557,Isabelle,2010-10-24,"Lyon, France",I'm 47 years old. I enjoy books and arts. I'm ...,within a few hours,1.00,f,...,4.71,4.78,4.86,"Available with a mobility lease only (""bail mo...",f,1,1,1,0,0.33
2,2,"Centre of old town,home sweet home",660135,Polali,2011-06-03,"Lyon, France","J'ai 34 ans , je suis animatrice auprès de per...",a few days or more,0.00,f,...,4.27,4.72,4.86,6938513221658,f,1,1,1,0,0.82
3,3,"Bel apartment, 2 rooms, Lyon center",670404,Sandrine,2011-06-06,"Lyon, France","We are a family with 3 daughters, aged 16-14-1...",NaN,NaN,f,...,4.89,4.89,4.95,693861800177,f,1,1,1,0,0.12
167,167,Terrace Heart Strirring View Fourvière/Vieux Lyon,12511374,Isabelle,2014-02-23,"Lyon, France","Dynamique, sportive, aimant voyager (surtout l...",within a few hours,1.00,t,...,4.70,4.86,4.87,6938513023403,f,1,1,1,0,1.32
186,186,Agréable T2 Lyon1er/Croix Rousse,14790563,Isabelle,2014-04-27,"Lyon, France",Il s'agit d'un appartement que j'ai rénové il ...,NaN,NaN,f,...,4.88,4.80,4.88,6938112676984,f,1,1,1,0,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9789,9789,Suite Wutaï,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,5.00,5.00,5.00,6900958902345,t,17,17,17,0,1.00
9885,9885,Suite Dounia,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900389034546,t,17,17,17,0,NaN
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9888,9888,Havre de Paix au Cœur du 7ème,666633599,Adrian,2024-12-12,NaN,NaN,NaN,NaN,f,...,NaN,NaN,NaN,6938712751252,f,1,1,1,0,NaN

In [25]:
#Convertir archivo filtrado a CSV
filtro1.to_csv('Filtro_Host_Name.csv')

**FILTRO PARA LOS HOST QUE SE HAYAN UNIDO A AIRBNB "DESPUÉS DEL AÑO 2020"**

In [18]:
filtro2=df[(df["host_since"]>="2020-01-01")]
filtro2

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
159,159,"Standing, 2 rooms, 110 sq, Place Bellecour",451047676,Aline,2022-03-24,"Lyon, France",je suis une gérante d'une conciergerie sur Lyo...,within an hour,1.00,f,...,4.77,4.96,4.96,6938213041302,f,22,21,21,0,0.38
161,161,Amazing Artistic Flat Fit 4 - Vieux Lyon,402191311,GuestReady,2021-05-18,NaN,"Hi there!\n\nWe're GuestReady, a professional ...",NaN,NaN,f,...,4.68,4.87,4.96,6938512563840,f,13,13,13,0,1.98
1367,1367,La Suite Mercière - Loft de luxe en plein centre,518347642,Marie & Mathilde,2023-06-05,"Meyzieu, France","Mère et fille, nous aimons offrir le meilleur ...",within an hour,1.00,f,...,4.89,4.94,4.86,6938212471772,f,11,11,11,0,0.33
1423,1423,Centre Presqu'Ile - Bel appartement 4 pers.,369826491,WeHost,2020-09-29,"Lyon, France",NaN,within an hour,0.99,f,...,4.53,4.70,4.93,6938212688439,t,41,41,41,0,1.55
1622,1622,Studio Cosy au Cœur de la Part Dieu,451047676,Aline,2022-03-24,"Lyon, France",je suis une gérante d'une conciergerie sur Lyo...,within an hour,1.00,f,...,4.79,4.81,4.83,6938612550549,t,22,21,21,0,1.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9885,9885,Suite Dounia,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900389034546,t,17,17,17,0,NaN
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9888,9888,Havre de Paix au Cœur du 7ème,666633599,Adrian,2024-12-12,NaN,NaN,NaN,NaN,f,...,NaN,NaN,NaN,6938712751252,f,1,1,1,0,NaN
9890,9890,L’opéra,417340177,Fifa,2021-08-07,"Lyon, France",NaN,within an hour,1.00,NaN,...,NaN,NaN,NaN,Exempt - hotel-type listing,t,5,4,4,0,NaN

In [34]:
#Convertir archivo filtrado a CSV
filtro2.to_csv('Filtro_Host_Since.csv')

**FILTRO PARA LOS HOST QUE RESPONDEN "A MÁS TARDAR EN 1 DÍA"**

In [19]:
filtro3=df[(df["host_response_time"]=="within a day")| (df["host_response_time"]=="within an hour")|(df["host_response_time"]=="within a few hours")]
filtro3

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,"Duplex avec vue, centre ville",269557,Isabelle,2010-10-24,"Lyon, France",I'm 47 years old. I enjoy books and arts. I'm ...,within a few hours,1.00,f,...,4.71,4.78,4.86,"Available with a mobility lease only (""bail mo...",f,1,1,1,0,0.33
1,1,Nice Flat in the center of Lyon,411285,Clementine,2011-02-26,"Lyon, France",Je travaille dans le cinéma et je voyage beauc...,within an hour,1.00,f,...,4.80,4.96,4.88,6938113058353,f,1,1,1,0,0.15
4,4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,832917,Giuseppina,2011-07-18,"Rhône-Alpes, France","Mon pays d'origine est l'Italie, mais je résid...",within an hour,1.00,f,...,4.86,4.83,4.88,6938112368465,f,2,2,2,0,2.99
5,5,Clear &very central flat Vieux Lyon,1221417,Max,2011-09-28,"Lyon, France","Bonjour, \nNous sommes Max et Julie!\nOn se ré...",within an hour,1.00,f,...,4.54,4.93,4.89,6938512680042,t,1,1,1,0,2.29
6,6,very pleasant and located idealment,1308521,Anaïs,2011-10-18,"Lyon, France",Nous vivons à Lyon avec nos deux enfants depui...,within a few hours,1.00,f,...,4.64,4.93,4.75,6938724479937,f,1,1,1,0,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9885,9885,Suite Dounia,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900389034546,t,17,17,17,0,NaN
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9889,9889,Le Duplex avec Rooftop,12466813,Hugues,2014-02-22,"Lyon, France",NaN,within an hour,1.00,f,...,NaN,NaN,NaN,6938713431341,f,1,1,1,0,NaN
9890,9890,L’opéra,417340177,Fifa,2021-08-07,"Lyon, France",NaN,within an hour,1.00,NaN,...,NaN,NaN,NaN,Exempt - hotel-type listing,t,5,4,4,0,NaN

In [27]:
#Convertir archivo filtrado a CSV
filtro3.to_csv('Filtro_Host_Response.csv')

**FILTRO PARA LAS FILAS "MÚLTIPLOS DE 200"**

In [20]:
filtro4=df.iloc[ [200,400,600,800,1000,1200,1400,1600,1800,2000,2200,
                  2400,2600,2800,3000,3200,3400,3600,3800,4000,4200,4400,
                  4600,4800,5000,5200,5400,5600,5800,6000,6200,6400,6600,6800,
                  7000,7200,7400,7600,7800,8000,8200,8400,8600,8800,9000,
                  9200,9400,9600,9800] , :]  #Filas no consecutivas
filtro4

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
200,200,Joli T3 slopes of the Croix Rousse,15781138,Pierre,2014-05-20,"Lyon, France","Bonjour, je suis artiste dramatique, coach et ...",within an hour,1.00,t,...,4.68,4.96,4.88,6938112978179,f,2,2,2,0,0.83
400,400,Room 2 pers. in the center of LYON,21333522,Patrick,2014-09-14,"Lyon, France",NaN,within an hour,1.00,t,...,4.84,4.93,4.94,6938112421123,f,1,0,0,0,3.35
600,600,Appartement central avec vue sur Fourvière,3754633,Xavier,2012-10-04,"Lyon, France",Amoureux des voyages .. je loue mon appartemen...,within an hour,1.00,t,...,4.95,4.88,4.88,6938112380343,f,2,2,2,0,2.82
800,800,Cosy apartment center Confluence,41141713,Dhubraska,2015-08-11,"Lyon, France",NaN,NaN,NaN,f,...,4.78,4.89,4.78,NaN,f,1,1,1,0,0.08
1000,1000,T2 cosy à Lyon,47658447,Olivia,2015-10-28,"Lyon, France",NaN,NaN,NaN,f,...,NaN,NaN,NaN,NaN,f,1,1,1,0,NaN
1200,1200,Comfortable flat near the center !,24418607,Elsa,2014-12-02,NaN,NaN,NaN,NaN,f,...,4.00,5.00,3.50,NaN,f,1,1,1,0,0.02
1400,1400,Appartement charmant et agréable,65733530,Clémence,2016-04-04,"Lyon, France","J'aime les voyages, les rencontres, la cuisine...",NaN,NaN,f,...,5.00,5.00,5.00,NaN,f,1,1,1,0,0.01
1600,1600,studio lyon euro 2016,75522476,Franck,2016-06-03,"Rillieux-la-Pape, France",NaN,NaN,NaN,f,...,NaN,NaN,NaN,NaN,t,1,1,1,0,NaN
1800,1800,Studio Saxe Gambetta,38906298,Valentine,2015-07-19,"Lyon, France",NaN,NaN,NaN,f,...,NaN,NaN,NaN,NaN,f,1,1,1,0,NaN
2000,2000,Chambre privée - Lyon centre,23527477,Noréa,2014-11-09,"Lyon, France",NaN,NaN,NaN,f,...,4.96,5.00,5.00,NaN,t,1,0,0,0,0.24
2200,2200,GRANDE CHAMBRE PROCHE SANS SOUCI,122821014,Margot,2017-03-27,"Guéret, France",Amatrice de randonnées et de voyages entre ami...,NaN,NaN,NaN,...,5.00,5.00,5.00,NaN,f,2,0,0,0,0.02
2400,2400,Nice appartment at Saxe Gambetta' station,19045862,Julia,2014-07-28,"Lyon, France",Bonjour ! \nJe m’appelle Julia et je vis à Lyo...,within a few hours,1.00,t,...,4.93,4.86,4.63,6938313297829,f,1,1,1,0,2.82
2600,2600,Appartement lumière 10 min de l’hyper centre,123083720,Pierre,2017-03-28,"Lyon, France",NaN,NaN,NaN,f,...,5.00,5.00,5.00,NaN,f,1,1,1,0,0.01
2800,2800,HONORÊ - SUITE 3 MARIES (4 PERS),153244990,Carine & Daniel,2017-10-04,"Lentilly, France",NaN,within an hour,1.00,f,...,4.60,4.97,4.90,6938512350638,t,22,20,20,0,0.47
3000,3000,Coeur de Lyon - Bel Appartement 54m² + Parking,178440593,Jocelyne,2018-03-14,NaN,NaN,within a few hours,1.00,t,...,4.89,4.89,4.95,6938212495627,f,1,1,1,0,1.35
3200,3200,Charmant appartement avec terrasse proche métro,30646292,Eugénie,2015-04-05,"Paris, France",NaN,NaN,NaN,f,...,4.78,4.92,4.80,6938713081646,f,1,1,1,0,0.63
3400,3400,Confortable studio au coeur de la Part-dieu !,80055338,Delphine Et Karim,2016-06-26,"Lyon, France",NaN,within an hour,1.00,t,...,4.92,4.94,4.87,6938612934391,f,3,3,3,0,10.71
3600,3600,The ground floor from the top of the slopes,227578716,Leo,2018-11-26,"Lyon, France",NaN,within an hour,1.00,t,...,4.85,4.91,4.88,6938112680944,f,1,1,1,0,1.60
3800,3800,Le Cocon Emeraude,52764609,Manon,2015-12-30,"Lyon, France","Bonjour,_x000D_\n_x000D_\nJusqu'ici, j'ai eu l...",within an hour,1.00,f,...,4.87,4.83,4.71,6938712870127,f,13,13,13,0,1.78
4000,4000,"Studio neuf, avec charme de l'ancien",146421850,Sophie,2017-08-17,"Lyon, France","Je suis Sophie, j'habite à Lyon en France. J'a...",within an hour,1.00,f,...,4.76,4.95,4.74,6938312590026,t,1,1,1,0,1.58
4200,4200,Chambre séparée dans duplex proche gare Perrache,8348309,Charlotte,2013-08-23,"Lyon, France","My name is Charlotte, i'm 30, i live in Lyon a...",NaN,NaN,f,...,5.00,5.00,5.00,NaN,f,1,0,0,0,0.02
4400,4400,Chambre chez Benjamin face au Rhône à Lyon 7,308229559,Benjamin,2019-11-09,"Lyon, France",NaN,within an hour,0.88,t,...,4.75,4.85,4.75,NaN,f,1,0,0,0,2.56
4600,4600,Superbe Appartement dans le 6eme Lyonnais !,18414194,Lise,2014-07-19,"Paris, France","Hello, je suis Lise ✨\n\nPassionnée par les ar...",NaN,NaN,f,...,4.00,5.00,5.00,NaN,f,1,1,1,0,0.02
4800,4800,Sand - Renovated top floor apartment,10758726,Axel,2013-12-22,"Lyon, France",The ONLY PLACE propose une sélection d’adresse...,within a day,0.81,f,...,NaN,NaN,NaN,6938212849973,f,9,9,9,0,NaN
5000,5000,Chambre pour 3 personnes - Hotel 4*,353185794,Hôtel Charlemagne,2020-07-03,"Lyon, France","Bonjour,\nJe serais ravi de vous faire découvr...",NaN,NaN,f,...,4.67,4.85,4.70,NaN,t,2,0,0,0,0.84
5200,5200,Appartement à proximité des berges du Rhône,395619148,Marie-France,2021-04-05,NaN,NaN,NaN,NaN,f,...,4.99,4.97,4.65,6938712895069,f,1,1,1,0,1.76
5400,5400,Grand duplex familial proche metro Valmy,4603373,Camille,2013-01-06,"Lyon, France","Bonjour. Lyonnaise depuis quelques années, je ...",NaN,NaN,f,...,5.00,5.00,5.00,6938913108514,f,1,1,1,0,0.03
5600,5600,Bel appartement dans Lyon,11010197,Marie-Laure,2014-01-04,"Lyon, France",Je suis une jeune française diplômée en ostéop...,within a few hours,0.90,t,...,4.68,4.71,4.14,6938313509150,f,1,1,1,0,1.03
5800,5800,Lyon Appartement Spacieux idéal Fête des Lumières,356215869,Joséphine,2020-07-13,"Lyon, France",NaN,a few days or more,0.00,f,...,NaN,NaN,NaN,6938713176270,f,1,1,1,0,NaN
6000,6000,Appartement Gare Part Dieu 40m2,447070993,Iris,2022-02-27,"Lyon, France",NaN,within an hour,1.00,f,...,4.90,5.00,5.00,6938613232321,f,1,1,1,0,0.64
6200,6200,Bel appartement en plein cœur de Lyon,415505540,Lilly,2021-07-27,NaN,NaN,NaN,NaN,f,...,5.00,5.00,4.57,6938913460979,f,1,0,0,0,0.28
6400,6400,Appartement T3 moderne Metro D et grande terrasse,45456156,Rémy,2015-09-30,"Lyon, France",NaN,within an hour,1.00,t,...,4.72,4.89,4.76,6938813364107,f,1,1,1,0,3.24
6600,6600,"Studio-Loft avec vue, Hôtel-Dieu",7576474,Mohom,2013-07-18,NaN,NaN,within an hour,0.99,t,...,5.00,5.00,4.94,6938313043154,f,14,14,14,0,1.35
6800,6800,Appartement très bien situé,107666935,Juliette,2016-12-18,"Lyon, France",NaN,a few days or more,0.33,f,...,NaN,NaN,NaN,6938713462520,f,2,2,2,0,NaN
7000,7000,Chambre 2 Pers - Salle de bain et Accès privés,131497939,Gaëtan,2017-05-22,"Lyon, France",NaN,NaN,NaN,f,...,4.88,4.90,4.74,NaN,f,1,0,0,0,5.44
7200,7200,Appartement familial canut,7391419,Félicie Et Mathias,2013-07-10,"Lyon, France",We live in Lyon. Felicie is an art historian o...,NaN,NaN,f,...,4.67,5.00,5.00,6938113551073,f,1,1,1,0,0.15
7400,7400,Superbe T2 des Canuts en plein coeur de Lyon,48769699,Maxime,2015-11-11,"Lyon, France",NaN,within a few hours,1.00,f,...,4.82,4.91,4.73,6938113590566,f,1,1,1,0,0.60
7600,7600,Chez Maud et Stéphane - Lyon Part-Dieu,66467823,Stéphane,2016-04-09,"Lyon, France",NaN,NaN,NaN,f,...,4.80,4.84,4.76,6938313643168,f,1,1,1,0,1.63
7800,7800,Skyline-Vitton Loft72,15719632,Anthony,2014-05-19,"Lyon, France",Agent immobilier et Partenaire Local AIRBNB à ...,within an hour,0.90,f,...,4.86,4.81,4.95,6938613681489,f,10,9,9,0,1.42
8000,8000,Dify Mazenod - Préfecture,507472339,Tiphaine & Anne,2023-03-28,"Lyon, France",NaN,NaN,NaN,f,...,4.83,4.63,4.79,6938313627332,t,35,35,35,0,1.87
8200,8200,Alma - Charmant apt 2 chambres,337698666,Agence COCOONR / BOOK&PAY,2020-02-20,"Rennes, France",Spécialistes de la location de courts et moyen...,NaN,NaN,f,...,5.00,5.00,5.00,6938624366039,t,43,43,43,0,0.40
8400,8400,Hidden garden in Lyon central,474151277,Jovi And Timéo,2022-08-09,NaN,NaN,within an hour,1.00,f,...,4.67,4.40,4.03,6910272612817,t,2,2,2,0,9.45
8600,8600,74 Gerland 1,532176426,Lina,2023-08-16,NaN,NaN,within an hour,1.00,f,...,4.28,4.53,4.47,6938713601981,t,78,78,78,0,4.01
8800,8800,Romantic Suite Right in the center of Lyon,576107285,Sebastien,2024-05-06,NaN,NaN,within an hour,0.92,f,...,4.33,4.71,4.67,Exempt - hotel-type listing,t,4,4,4,0,3.21
9000,9000,Appartement cosy,51296698,Chloé,2015-12-14,"Lyon, France",NaN,NaN,NaN,f,...,5.00,2.00,5.00,6938724459844,f,1,1,1,0,0.22
9200,9200,Montgolfier Masséna,532176426,Lina,2023-08-16,NaN,NaN,within an hour,1.00,f,...,4.26,4.57,4.70,Exempt - hotel-type listing,t,78,78,78,0,6.00
9400,9400,Chambre Lyon 7,122128181,Abderemane,2017-03-22,"Lyon, France",NaN,within an hour,1.00,f,...,NaN,NaN,NaN,NaN,f,1,0,0,0,NaN
9600,9600,Petit studio en plein centre ville,413301706,Agathe,2021-07-16,NaN,NaN,within an hour,1.00,f,...,5.00,5.00,5.00,6938124532660,f,1,1,1,0,1.00
9800,9800,Appartement d’artiste avec vue,43182634,Ghyslaine,2015-09-02,"Lyon, France",NaN,within a day,0.75,f,...,NaN,NaN,NaN,6938124541767,f,1,1,1,0,NaN

In [28]:
#Convertir archivo filtrado a CSV
filtro4.to_csv('Filtro_Filas_200.csv')

**FILTRO PARA LOSTIPOS DE CUARTO "ENTIRE HOME" Y "PRIVATE ROOM"**

In [38]:
filtro5=df[(df["room_type"]=="Entire home/apt") | (df["room_type"]=="Private room")]
filtro5

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
0,0,"Duplex avec vue, centre ville",269557,Isabelle,2010-10-24,"Lyon, France",I'm 47 years old. I enjoy books and arts. I'm ...,within a few hours,1.00,f,...,4.71,4.78,4.86,"Available with a mobility lease only (""bail mo...",f,1,1,1,0,0.33
1,1,Nice Flat in the center of Lyon,411285,Clementine,2011-02-26,"Lyon, France",Je travaille dans le cinéma et je voyage beauc...,within an hour,1.00,f,...,4.80,4.96,4.88,6938113058353,f,1,1,1,0,0.15
2,2,"Centre of old town,home sweet home",660135,Polali,2011-06-03,"Lyon, France","J'ai 34 ans , je suis animatrice auprès de per...",a few days or more,0.00,f,...,4.27,4.72,4.86,6938513221658,f,1,1,1,0,0.82
3,3,"Bel apartment, 2 rooms, Lyon center",670404,Sandrine,2011-06-06,"Lyon, France","We are a family with 3 daughters, aged 16-14-1...",NaN,NaN,f,...,4.89,4.89,4.95,693861800177,f,1,1,1,0,0.12
4,4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,832917,Giuseppina,2011-07-18,"Rhône-Alpes, France","Mon pays d'origine est l'Italie, mais je résid...",within an hour,1.00,f,...,4.86,4.83,4.88,6938112368465,f,2,2,2,0,2.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9888,9888,Havre de Paix au Cœur du 7ème,666633599,Adrian,2024-12-12,NaN,NaN,NaN,NaN,f,...,NaN,NaN,NaN,6938712751252,f,1,1,1,0,NaN
9889,9889,Le Duplex avec Rooftop,12466813,Hugues,2014-02-22,"Lyon, France",NaN,within an hour,1.00,f,...,NaN,NaN,NaN,6938713431341,f,1,1,1,0,NaN
9890,9890,L’opéra,417340177,Fifa,2021-08-07,"Lyon, France",NaN,within an hour,1.00,NaN,...,NaN,NaN,NaN,Exempt - hotel-type listing,t,5,4,4,0,NaN

In [39]:
#Convertir archivo filtrado a CSV
filtro5.to_csv('Tipos_Cuarto.csv')

**FILTRO PARA LOS  QUE CUENTEN A LO MUCHO CON 4 CAMAS**

In [47]:
filtro6=df[(df["beds"]<=4)]
filtro6

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
1,1,Nice Flat in the center of Lyon,411285,Clementine,2011-02-26,"Lyon, France",Je travaille dans le cinéma et je voyage beauc...,within an hour,1.00,f,...,4.80,4.96,4.88,6938113058353,f,1,1,1,0,0.15
2,2,"Centre of old town,home sweet home",660135,Polali,2011-06-03,"Lyon, France","J'ai 34 ans , je suis animatrice auprès de per...",a few days or more,0.00,f,...,4.27,4.72,4.86,6938513221658,f,1,1,1,0,0.82
3,3,"Bel apartment, 2 rooms, Lyon center",670404,Sandrine,2011-06-06,"Lyon, France","We are a family with 3 daughters, aged 16-14-1...",NaN,NaN,f,...,4.89,4.89,4.95,693861800177,f,1,1,1,0,0.12
4,4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,832917,Giuseppina,2011-07-18,"Rhône-Alpes, France","Mon pays d'origine est l'Italie, mais je résid...",within an hour,1.00,f,...,4.86,4.83,4.88,6938112368465,f,2,2,2,0,2.99
5,5,Clear &very central flat Vieux Lyon,1221417,Max,2011-09-28,"Lyon, France","Bonjour, \nNous sommes Max et Julie!\nOn se ré...",within an hour,1.00,f,...,4.54,4.93,4.89,6938512680042,t,1,1,1,0,2.29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,9886,Suite Rumba,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900078928345,t,17,17,17,0,NaN
9887,9887,Suite Zelie,651608878,Pablo,2024-09-12,NaN,NaN,within an hour,0.87,f,...,NaN,NaN,NaN,6900399034456,t,17,17,17,0,NaN
9888,9888,Havre de Paix au Cœur du 7ème,666633599,Adrian,2024-12-12,NaN,NaN,NaN,NaN,f,...,NaN,NaN,NaN,6938712751252,f,1,1,1,0,NaN
9889,9889,Le Duplex avec Rooftop,12466813,Hugues,2014-02-22,"Lyon, France",NaN,within an hour,1.00,f,...,NaN,NaN,NaN,6938713431341,f,1,1,1,0,NaN
9890,9890,L’opéra,417340177,Fifa,2021-08-07,"Lyon, France",NaN,within an hour,1.00,NaN,...,NaN,NaN,NaN,Exempt - hotel-type listing,t,5,4,4,0,NaN

In [48]:
#Convertir archivo filtrado a CSV
filtro6.to_csv('Numero_Camas.csv')

**FILTRO PARA LOS QUE SEAN SUPER HOST**

In [50]:
filtro7=df[(df["host_is_superhost"]=="t")]
filtro7

,Unnamed: 0,name,host_id,host_name,host_since,host_location,host_about,host_response_time,host_response_rate,host_is_superhost,...,review_scores_cleanliness,review_scores_checkin,review_scores_location,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_entire_homes.1,calculated_host_listings_count_shared_rooms,reviews_per_month
7,7,Studio apartment near opera city centre,1319577,Emmanuel,2011-10-21,"Lyon, France",pour avoir voyagé dans plus de 50 pays depuis ...,within a few hours,1.00,t,...,4.92,4.92,5.00,6938113043606,f,1,1,1,0,0.12
10,10,"★SAXE & THE CITY★ 90m², Quiet, Balcony, Clean+...",1738855,Amael Et Ida,2012-02-12,"Lyon, France","Avides de voyages, nous avons commencé à louer...",within an hour,1.00,t,...,4.74,4.90,4.72,6938312360788,t,1,1,1,0,2.32
11,11,Studio situé au cœur historique de Lyon,1848025,Anne-Marie,2012-03-03,"Lyon, France",Habitant le centre ville de Lyon dpuis fort lo...,within an hour,1.00,t,...,4.93,4.96,4.92,6938112647884,f,1,1,1,0,1.40
17,17,"Mezzo, Nice and quiet two rooms flat",3038226,Sophie,2012-07-24,"Lyon, France","From west of France, on the Loir castles, I am...",within an hour,1.00,t,...,4.30,4.85,4.80,6938112414193,f,6,5,5,0,0.14
20,20,A LOVELY BEDROOM IN VIEUX-LYON,3165326,Mila & Julien,2012-08-05,"Lyon, France","My name is Julien, I have been doing airBNB fo...",within an hour,1.00,t,...,4.73,4.83,4.92,NaN,f,3,2,2,0,2.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9839,9839,Petit Cocon Douillet au cœur du 1er arrdt,18157048,Estelle Et Laurent,2014-07-15,"Saint-Pierre-la-Palud, France",NaN,within an hour,1.00,t,...,5.00,5.00,5.00,6938013343937,f,2,2,2,0,1.00
9849,9849,Appartement proche part dieu,38787510,Fabien,2015-07-17,"Lyon, France",NaN,within an hour,1.00,t,...,NaN,NaN,NaN,6938324544582,f,2,2,2,0,NaN
9855,9855,4# Chambre privée à proximité de Jean-Macé,144940438,Alexandre Amine,2017-08-08,"Lyon, France","I G : @this_is_adj\n\nAlex, 27 ans | Lyon, Fra...",within an hour,0.99,t,...,NaN,NaN,NaN,NaN,f,5,1,1,1,NaN
9860,9860,Pop Opera Appart vue sur toits,170737620,Nathalie,2018-01-30,NaN,"Bonjour à Tous, je m'appelle Nathalie, j'appr...",within an hour,1.00,t,...,NaN,NaN,NaN,"Available with a mobility lease only (""bail mo...",f,3,3,3,0,NaN
9884,9884,Le Studio Jacobins,42716784,Carl,2015-08-27,"Lyon, France","Français d’origine togolaise, j’ai pas mal voy...",within an hour,1.00,t,...,NaN,NaN,NaN,NaN,t,12,9,9,0,NaN

In [51]:
#Convertir archivo filtrado a CSV
filtro7.to_csv('Filtro_Host_Superhost.csv')

**FILTRO PARA LAS COLUMNAS IMPARES**

In [24]:
filtro8=df.iloc[:,1::2]
filtro8

,name,host_name,host_location,host_response_time,host_is_superhost,host_listings_count,host_identity_verified,latitude,property_type,accommodates,...,maximum_nights_avg_ntm,availability_60,availability_365,number_of_reviews_ltm,last_review,review_scores_cleanliness,review_scores_location,instant_bookable,calculated_host_listings_count_entire_homes,calculated_host_listings_count_shared_rooms
0,"Duplex avec vue, centre ville",Isabelle,"Lyon, France",within a few hours,f,1.0,t,45.763140,Entire rental unit,5,...,1125.0,14,302,1,2024-06-30,4.71,4.86,f,1,0
1,Nice Flat in the center of Lyon,Clementine,"Lyon, France",within an hour,f,1.0,t,45.768420,Entire rental unit,4,...,15.0,53,83,2,2024-12-08,4.80,4.88,f,1,0
2,"Centre of old town,home sweet home",Polali,"Lyon, France",a few days or more,f,1.0,t,45.759300,Entire rental unit,2,...,30.0,57,87,2,2024-06-04,4.27,4.86,f,1,0
3,"Bel apartment, 2 rooms, Lyon center",Sandrine,"Lyon, France",NaN,f,1.0,t,45.768845,Entire condo,2,...,730.0,0,98,0,2019-12-28,4.89,4.95,f,1,0
4,Quartier Terreaux 4/6 pers. Hyper centre / Clim,Giuseppina,"Rhône-Alpes, France",within an hour,f,5.0,t,45.766950,Entire rental unit,6,...,1125.0,49,169,32,2024-11-24,4.86,4.88,f,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9886,Suite Rumba,Pablo,NaN,within an hour,f,27.0,t,45.747560,Entire rental unit,5,...,365.0,34,339,0,NaN,NaN,NaN,t,17,0
9887,Suite Zelie,Pablo,NaN,within an hour,f,27.0,t,45.757020,Entire rental unit,6,...,365.0,42,323,0,NaN,NaN,NaN,t,17,0
9888,Havre de Paix au Cœur du 7ème,Adrian,NaN,NaN,f,1.0,t,45.737954,Entire rental unit,2,...,1125.0,41,89,0,NaN,NaN,NaN,f,1,0
9889,Le Duplex avec Rooftop,Hugues,"Lyon, France",within an hour,f,1.0,t,45.744800,Entire rental unit,4,...,365.0,60,365,0,NaN,NaN,NaN,f,1,0
9890,L’opéra,Fifa,"Lyon, France",within an hour,NaN,20.0,t,45.766985,Entire rental unit,2,...,365.0,57,362,0,NaN,NaN,NaN,t,4,0

In [52]:
#Convertir archivo filtrado a CSV
filtro8.to_csv('Filtro_Colum_Inpar.csv')